spring:
  application:
    name: DataMarket
  datasource:
    url: jdbc:mysql://localhost:3306/data_market
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
          starttls:
            enable: true
          ssl:
            enable: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

file:
  upload-path: D:/Learning/Senior/the_end/file/csvData/
